{{- $fullname := printf "%s-%s" .Release.Name "redis" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{- if .Values.secret.name -}}{{ .Values.secret.name }}{{- else -}}{{ $fullname }}-secret{{- end }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc }}
