{{- $fullname := printf "%s-%s" .Release.Name "redis" -}}
{{- $chartLabel := (printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    helm.sh/chart: {{ $chartLabel }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
