{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: {{ .Values.name | default .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: {{ .Values.component | default "service" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secret.type | default "Opaque" }}
{{- if .Values.secret.data }}
data:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- else }}
stringData:
  {{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}


