# Image configuration
image:
  registry: registry.k8s.io
  repository: ingress-nginx/controller
  tag: "v1.9.4"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: LoadBalancer
  externalIPs: []  # LoadBalancer가 자동으로 할당
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  annotations:
    # OpenStack LoadBalancer 설정 (카카오클라우드)
    openstack.org/load-balancer-provider: octavia
    openstack.org/load-balancer-floating-network-id: "EXTERNAL"
    openstack.org/load-balancer-floating-subnet-id: "EXTERNAL"
    service.beta.kubernetes.io/openstack-load-balancer-class: "octavia"

# Chart metadata
name: nginx-ingress
component: ingress-controller

controller:
  service:
    type: LoadBalancer
    externalIPs: []  # LoadBalancer가 자동으로 할당
    ports:
      http: 80
      https: 443
    nodePorts:
      http: 32058
      https: 30899
    annotations:
      # OpenStack LoadBalancer 설정 (카카오클라우드)
      openstack.org/load-balancer-provider: octavia
      openstack.org/load-balancer-floating-network-id: "EXTERNAL"
      openstack.org/load-balancer-floating-subnet-id: "EXTERNAL"
      service.beta.kubernetes.io/openstack-load-balancer-class: "octavia"
  
  # 리소스 설정
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: 500m
      memory: 512Mi

# IngressClass 설정
ingressClassResource:
  enabled: true
  name: nginx
  default: true

# Tolerations - 마스터 노드에서 실행 허용
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# NodeSelector - 마스터 노드에서만 실행
nodeSelector:
  node-role.kubernetes.io/control-plane: ""

# Affinity for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - nginx-ingress
        topologyKey: kubernetes.io/hostname

# Pod configuration
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "10254"
  prometheus.io/path: "/metrics"

# Service account
serviceAccount:
  create: true
  name: ""

# RBAC
rbac:
  create: true

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 65534

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE

# Environment variables
env:
  POD_NAMESPACE: "ingress-nginx"
  POD_NAME: "nginx-ingress-controller"

# Health checks
livenessProbe:
  httpGet:
    path: /healthz
    port: 10254
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: 10254
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Ingress class
ingressClass: nginx

# Global SSL redirect 설정 비활성화 (Cloudflare에서 TLS 처리)
controller:
  config:
    ssl-redirect: "false"
    # HTTPS 처리 설정 (Cloudflare DNS 전용 모드 대응)
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "false"
