apiVersion: v2
name: redis
description: A Helm chart for Redis
type: application
version: 0.1.0
appVersion: "7.0"
keywords:
  - redis
  - database
  - cache
home: https://redis.io
sources:
  - https://github.com/redis/redis
maintainers:
  - name: INFRA Team
    email: infra@company.com
