# Default values for auth-service
# This is a YAML-formatted file.

# Import common values
import:
  - ../../../helm-common/values/common.yaml
# Override common values for auth-service
name: auth-service
component: auth-service
partOf: microservices
# Image configuration
image:
  registry: ""
  repository: docker.io/9september/auth-service
  tag: "cdcf237f22c1f94f3e0121a589ffaa7865f1f1d2" # This will be updated by CI/CD
# Replica count
replicaCount: 2
# Service configuration
service:
  enabled: true
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: auth.example.com
      paths:
        - path: /
          pathType: Prefix
          servicePort: 80
  tls: []
# ConfigMap configuration
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: "prod"
    SERVER_PORT: "8080"
    LOGGING_LEVEL_ROOT: "INFO"
# Secret configuration
secret:
  enabled: true
  type: Opaque
  stringData:
    JWT_SECRET: "your-jwt-secret-key"
    DATABASE_PASSWORD: "your-database-password"
# Environment variables
env:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
# Resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
# Pod configuration
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"
# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
# Service account
serviceAccount:
  create: true
  name: ""
# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL
