# Default values for auth-service
# This is a YAML-formatted file.

# Auth Service configuration
name: auth-service
component: auth-service
partOf: microservices

# Image configuration
image:
  registry: ""
  repository: docker.io/9september/auth-service
  tag: "00962a2be12f16818067b9bcc07707b85688da98"  # This will be updated by CI/CD

# Replica count
replicaCount: 2

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# Service configuration
service:
  enabled: true
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # CORS 설정
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://auth.youth-fi.com, https://youth-fi.com, https://www.youth-fi.com, http://localhost:5173, http://localhost:8082"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,PUT,POST,DELETE,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Authorization,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-user-Id"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"
  hosts:
    - host: "auth.youth-fi.com"  # Cloudflare 도메인
      paths:
        - path: /
          pathType: Prefix
          servicePort: 80

# ConfigMap configuration
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: "prod"
    SERVER_PORT: "8080"
    LOGGING_LEVEL_ROOT: "INFO"

# Secret configuration
secret:
  enabled: false

# Environment variables
env:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_FORWARD_HEADERS_STRATEGY: "framework"
  MANAGEMENT_SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"

  # From Secret: auth-secrets
  spring.datasource.url:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.datasource.url
  spring.datasource.username:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.datasource.username
  spring.datasource.password:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.datasource.password
  spring.datasource.driver-class-name:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.datasource.driver-class-name

  spring.data.redis.host:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.data.redis.host
  spring.data.redis.port:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.data.redis.port
  spring.data.redis.password:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.data.redis.password
  spring.data.redis.database:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: spring.data.redis.database
  jwt.key:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: jwt.key
  jwt.access.expiration:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: jwt.access.expiration
  jwt.refresh.expiration:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: jwt.refresh.expiration
  jwt.verification-expiration-ms:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: jwt.verification-expiration-ms
  email.from:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: email.from
  email.host:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: email.host
  email.port:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: email.port
  email.username:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: email.username
  email.password:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: email.password
  app.client.url:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: app.client.url
  auth.oauth2.clients.google.client-id:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.google.client-id
  auth.oauth2.clients.google.client-secret:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.google.client-secret
  auth.oauth2.clients.google.redirect-uri:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.google.redirect-uri
  auth.oauth2.clients.naver.client-id:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.naver.client-id
  auth.oauth2.clients.naver.client-secret:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.naver.client-secret
  auth.oauth2.clients.naver.redirect-uri:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.naver.redirect-uri
  auth.oauth2.clients.kakao.client-id:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.kakao.client-id
  auth.oauth2.clients.kakao.client-secret:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.kakao.client-secret
  auth.oauth2.clients.kakao.redirect-uri:
    valueFrom:
      secretKeyRef:
        name: auth-secrets
        key: auth.oauth2.clients.kakao.redirect-uri

# Resources
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Pod configuration
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"

startupProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 30

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 12

# Readiness probe (disabled)
readinessProbe: null

# Service account
serviceAccount:
  create: true
  name: ""

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # Spring Boot가 임시 파일을 생성할 수 있도록 수정
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL
