apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
spec:
  replicas: {{ .Values.applicationController.replicas }}
  selector:
    matchLabels:
      app: argocd-application-controller
  template:
    metadata:
      labels:
        app: argocd-application-controller
    spec:
      serviceAccountName: argocd-application-controller
      containers:
      - name: argocd-application-controller
        image: {{ .Values.applicationController.image.repository }}:{{ .Values.applicationController.image.tag }}
        imagePullPolicy: {{ .Values.applicationController.image.pullPolicy }}
        env:
        - name: ARGOCD_REDIS_SERVER
          value: "argocd-redis:6379"
        - name: ARGOCD_REDIS_DB
          value: "0"
        command:
        - argocd-application-controller
        volumeMounts:
        - name: argocd-cm
          mountPath: /app/config/controller
        - name: argocd-secret
          mountPath: /app/config/secret
        - name: argocd-rbac-cm
          mountPath: /app/config/rbac
        resources:
{{- toYaml .Values.applicationController.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: argocd-cm
        configMap:
          name: argocd-cm
      - name: argocd-secret
        secret:
          secretName: argocd-secret
      - name: argocd-rbac-cm
        configMap:
          name: argocd-rbac-cm
