apiVersion: v1
kind: Service
metadata:
  name: argocd-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
spec:
  selector:
    app: argocd-redis
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
  type: ClusterIP
