apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
spec:
  selector:
    app: argocd-repo-server
  ports:
  - name: repo-server
    port: 8081
    targetPort: 8081
  type: ClusterIP
