apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value }}
{{- end }}
