apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  selector:
    app: argocd-server
  ports:
  - name: http
    port: {{ .Values.server.service.ports.http }}
    targetPort: {{ .Values.server.service.ports.http }}
  - name: grpc
    port: {{ .Values.server.service.ports.grpc }}
    targetPort: {{ .Values.server.service.ports.grpc }}
  type: {{ .Values.server.service.type }}
