apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: argocd-server
        image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.server.service.ports.http }}
        - containerPort: {{ .Values.server.service.ports.grpc }}
        env:
{{- toYaml .Values.server.env | nindent 8 }}
        command:
        - argocd-server
        - --insecure
        - --staticassets
        - /shared/app
        volumeMounts:
        - name: argocd-cm
          mountPath: /app/config/controller
        - name: argocd-secret
          mountPath: /app/config/secret
        - name: argocd-rbac-cm
          mountPath: /app/config/rbac
        resources:
{{- toYaml .Values.server.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.server.service.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.server.service.ports.http }}
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: argocd-cm
        configMap:
          name: argocd-cm
      - name: argocd-secret
        secret:
          secretName: argocd-secret
      - name: argocd-rbac-cm
        configMap:
          name: argocd-rbac-cm
