apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: ARGOCD_SERVER_INSECURE
          value: "true"
        - name: ARGOCD_SERVER_DISABLE_AUTH
          value: "true"
        - name: ARGOCD_SERVER_INSECURE_BIND_ADDRESS
          value: "0.0.0.0"
        - name: ARGOCD_REDIS_SERVER
          value: "argocd-redis:6379"
        - name: ARGOCD_REDIS_DB
          value: "0"
        command:
        - argocd-server
        - --insecure
        - --staticassets
        - /shared/app
        volumeMounts:
        - name: argocd-cm
          mountPath: /app/config/controller
        - name: argocd-secret
          mountPath: /app/config/secret
        - name: argocd-rbac-cm
          mountPath: /app/config/rbac
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: argocd-cm
        configMap:
          name: argocd-cm
      - name: argocd-secret
        secret:
          secretName: argocd-secret
      - name: argocd-rbac-cm
        configMap:
          name: argocd-rbac-cm
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app: argocd-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 8081
    targetPort: 8081
  type: LoadBalancer
