apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # ArgoCD 서버 시크릿 키 (base64 인코딩된 값)
  server.secretkey: YWJjZGVmZ2hpams=  # abcdefghijk
  # OIDC 클라이언트 시크릿
  oidc.clientSecret: YXJnb2NkLXNlY3JldA==  # argocd-secret
  # ArgoCD 관리자 비밀번호 (admin)
  admin.password: JDJhJDEwJEVCNmdaNEg2Y2p3d3B2Q2ZaYUNLL1ZzT2dWY0pVZ29VcU5zQ1J0ZU5wTk5uQnE2V0E2  # $2a$10$EB6gZ4H6cjwwpvCfZaACK/VsOgVcJUgoUqNsCRteNpNNnBq6WA6
  # ArgoCD 관리자 비밀번호 해시
  admin.passwordMtime: MjAyNC0wMS0wMVQwMDowMDowMFo=  # 2024-01-01T00:00:00Z
