apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # ArgoCD 서버 설정
  server.insecure: "true"
  server.disable.auth: "true"
  server.staticassets: "/shared/app"
  
  # 리포지토리 설정
  repositories: |
    - type: git
      url: https://github.com/KE-WhyNot/INFRA
      name: infra-repo
      
  # 애플리케이션 설정
  application.instanceLabelKey: argocd.argoproj.io/instance
  application.instanceLabelValue: argocd
  
  # 로그 레벨
  log.level: info
  
  # UI 설정
  ui.default.repo.url: https://github.com/KE-WhyNot/INFRA
  
  # 리소스 제한
  controller.status.processors: "20"
  controller.operation.processors: "10"
  controller.self.heal.timeout.seconds: "5"
  controller.repo.server.timeout.seconds: "60"
  
  # 서버 설정
  server.rbac.log.enforce.enable: "true"
  server.enable.gzip: "true"
  
  # 리포지토리 서버 설정
  repo.server: argocd-repo-server:8081
  
  # Dex 설정 (인증용)
  dex.config: |
    connectors: []
    oidc:
      name: OIDC
      issuer: https://kubernetes.default.svc
      clientId: argocd
      clientSecret: $oidc.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
